### ISSUE TITLE
Unable to run plots for image matrices

### ISSUE THREAD

**Issue by ezekny** [alok-ai-lab/pyDeepInsight#18]
`fig, ax = plt.subplots(1, 4, figsize=(25, 7))
for i in range(0,4):
    cax = sns.heatmap(mat_train[i], cmap='hot',
                      linewidth=0.01, linecolor='dimgrey',
                      square=True, ax=ax[i], cbar=False)
    cax.axis('off')
plt.tight_layout()`

After running the above code, i was getting the following errors:

**ValueError                                Traceback (most recent call last)
[<ipython-input-30-582304a8fb0b>](https://localhost:8080/#) in <module>()
      3   cax = sns.heatmap(mat_train[i], cmap='hot',linewidth=0.01, 
      4                       linecolor='dimgrey',
----> 5                       square=True, ax=ax[i], cbar=False)
      6   cax.axis('off')
      7 plt.tight_layout()

5 frames
[/usr/local/lib/python3.7/dist-packages/pandas/core/internals/construction.py](https://localhost:8080/#) in _prep_ndarray(values, copy)
    553         values = values.reshape((values.shape[0], 1))
    554     elif values.ndim != 2:
--> 555         raise ValueError(f"Must pass 2-d input. shape={values.shape}")
    556 
    557     return values

ValueError: Must pass 2-d input. shape=(50, 50, 3)**

Pls help out.What should i do to get the error fixed. Thank you

**Comment by ezekny** [comment]
Oh! I am grateful, thank you.

**Comment by ezekny** [comment]
I have use the code and it works fine. However, the look was not like the one with `seaborn.` Is there a way by which this could be done? I have started with seaborn heatmap for plotting, is it possible to continue with it. I will need your suggestion on this. Thanks

**Comment by kaboroevich** [comment]
Is this issue resolved or did you close it by accident?

**Comment by ezekny** [comment]
No, it hasn't. It was closed by accident

**Comment by kaboroevich** [comment]
Please be mindful not to click "close with comment" when making a comment. While debugging seaborn plots is not an issue related to DeepInsight, I can try to help.

It looks like mat_train is the output of the `.transform` function in 'rgb' format, which returns an [N,M,3] matrix. I think what you are looking for is to add `format='scalar'` to the transform function to return only [N,M] matrices. 

If that doesn't help, can you explain what you are trying to plot.

**Comment by ezekny** [comment]
With all due respect, i am grateful, you have really help me. it works fine
now after adding  format='scalar' to the transform function. I appreciate

**Comment by ezekny** [comment]
Another challenge please. I like to have each image stored as png format  i used the following code
**
fig, ax = plt.subplots(1, 4, figsize=(25, 7))
for i in range(0,4):
    cax = sns.heatmap(mat_train[i], cmap='hot',
                      linewidth=0.01, linecolor='dimgrey',
                      square=True, ax=ax[i], cbar=False)
    cax.axis('off')
    plt.savefig("/whole_figure"+ str(i)+".png", dpi=300)
**
![image](https://user-images.githubusercontent.com/18138003/156351301-2f806121-b837-4058-937f-595b8c1a0dff.png)

The result of what i was getting is shown in the figure above. However, i would like the image to be without scale and other empty cell to be removed. Can i get help on this too. Thanks

**Comment by kaboroevich** [comment]
The four subplots come from the 4 in `subplots(1, **4**)`. For remove the scale, see the StackOverflow question "[How to remove or hide y-axis ticklabels from a matplotlib / seaborn plot](https://stackoverflow.com/questions/63756623/how-to-remove-or-hide-y-axis-ticklabels-from-a-matplotlib-seaborn-plot)".

**Comment by ezekny** [comment]
@kaboroevich :This suggestion worked fine. i was able to generate the image one by one using the recommended link. Thank you.

**Comment by ezekny** [comment]
Still on the project, what will i use to save a figure or a plot to an array, and how can it be referenced in imshow ( )  or plot.show(). Thank you

**Comment by kaboroevich** [comment]
Sorry, these questions are beyond the scope of this package and I do not know the answers off-hand. I would suggest asking on a more general forum like [StackOverflow](https://stackoverflow.com/) or similar.
