### ISSUE TITLE
How to  take the image matrices to CNN

### ISSUE THREAD

**Issue by ezekny** [alok-ai-lab/pyDeepInsight#19]
After going through the python code for the DeepInsight, i was very glad to see a breakthrough to my project. But I could not understand how to take the image matrices to CNN as concluded from the code. Can you please help me on this. Thanks

**Comment by kaboroevich** [comment]
Please see the [DeepInsight SqueezeNet Example](https://github.com/alok-ai-lab/pyDeepInsight/blob/master/examples/pytorch_squeezenet.md) in the `/examples/` directory. This example describes how to take the output of the ImageTransformer and use it to train a SqueezeNet CNN.

If you decide to use the same SqueezeNet as in the example, pay particular attention to correcting the number of output classes from the model.

**Comment by ezekny** [comment]
Thank you
