### ISSUE TITLE
How to plot a 2D image space formed after applying t-SNE 

### ISSUE THREAD

**Issue by ezekny** [alok-ai-lab/pyDeepInsight#21]
I have been implementing the squeezeNet and wanted to plot the 2D image of t-SNE and how to apply the Convex Hull for rotation. Kindly assist on the way forward on this. Thank you

**Comment by kaboroevich** [comment]
The pre-rotated t-SNE positions are not stored. Two possible options are

1. Set `plot=True` of the [pyDeepInsight.ImageTransformer.fit](https://github.com/alok-ai-lab/pyDeepInsight/blob/7710ece2737be70c3d11e3a5ac1a4cfea1ac8ba6/pyDeepInsight/image_transformer.py#L67) method as seen in README.md. This will return an image of the t-SNE reduced features (blue), convex full (red), and minimum bounding rectangle (green) prior to rotation. There is no way to modify this image.
2. Plot the post-rotation reduced features that are stored in the private attribute `ImageTransformer._xrot`.
