### ISSUE TITLE
Error using pyDeepInsight library

### ISSUE THREAD

**Issue by superbunny38** [alok-ai-lab/pyDeepInsight#24]
Hello, I was trying to fit some non-image data to CNN model, so I needed your library :)
However, I ran into  this error:
![image](https://user-images.githubusercontent.com/48243487/177544822-b9966219-8671-4ca3-b23e-31a4bcf7d55a.png)

I was able to successfully download your library using python commands as you wrote on github, but couldn't load them, as below image shows as well.
![image](https://user-images.githubusercontent.com/48243487/177545045-7e2547cc-f237-40af-afb9-90f1f5a5195a.png)

I also tried cloning your repository and running the commands, but compiling [image_transformer.py](https://github.com/alok-ai-lab/pyDeepInsight/blob/master/pyDeepInsight/image_transformer.py) itself also gave me an error.

Thank you for sharing your work, and I look forward to your reply :)

**Comment by kaboroevich** [comment]
The type hinting I had used is only supported in Python 3.9+. I think I corrected it so that you can now use it with earlier versions. Please re-install pyDeepInsight from GitHub and try again. Let us know if the issue still persists.

**Comment by superbunny38** [comment]
Thank you so much for your reply!:)
I'll try using your library, and write to you if there is any issue :D
