### ISSUE TITLE
Using pyDeepInsight for multidimensional data

### ISSUE THREAD

**Issue by martin-jeremy** [alok-ai-lab/pyDeepInsight#25]
Hi !
I hope you will be able to help me.

I'm currently working on transcriptomics data. I try DeepInsight to classify RNA seq data (one column per experiment, one gene per row) and it worked pretty well.

What I want to do now, is to use DeepInsight to classify single cell RNA seq **dataset**. For example, I have:

**- 20 datasets** _each datasets contains 30.000 rows, but they have **different number of columns** (one cell = one column)._
**- Each cells** _are already identified._

I know if my dataset are from "HEALTHY" sample or if it "DISEASE" sample. There are an approach to use DeepInsight to know if a new dataset are from HEALTHY or from DISEASE ?

Perhaps a kind of "multi-layered" image ?

Thanks for your help !

**Comment by kaboroevich** [comment]
If I understand correctly, you have 20 samples (datasets) each consisting of multiple layers (cells) and features (genes) and you want to predict whether or not a new dataset/sample is health or diseased? While it's possible you could apply DeepInsight to your data, a sample size of 20 is likely too small to train a CNN.

Multi-layered analysis (equivalent to multiple channels in standard CNN methods) is possible if each layer matches. Please see the [DeepInisght-3D repository](https://github.com/alok-ai-lab/DeepInsight3D_pkg) for a 3 layer/channel implementation in MatLab.

**Comment by martin-jeremy** [comment]
Okay, I understand that.

How many sample you think its necessary to trian a CNN efficiently ? 

I will give a look to DeepInsight-3D. Thank's !

**Comment by kaboroevich** [comment]
I'm not certain I can answer that.
