### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_grad_cam'

### ISSUE THREAD

**Issue by ofakduman** [alok-ai-lab/pyDeepInsight#28]
Hi
I encountered this error while trying to import the library. What would you suggest me to do?
Best Regards

![image](https://user-images.githubusercontent.com/61577706/199361866-d5cab47e-4f37-4d02-9598-dd089719865b.png)

**Comment by kaboroevich** [comment]
It appears the pyDeepInsight requirements haven't been updated. Please install [pytorch-grad-cam](https://github.com/jacobgil/pytorch-grad-cam) and [torchcam](https://frgfm.github.io/torch-cam/) independently.

`pip install grad-cam`
`pip install torchcam`
