### ISSUE TITLE
ImportError 

### ISSUE THREAD

**Issue by ashutoshsinha25** [alok-ai-lab/pyDeepInsight#29]
I'm working in Colab notebook, I installed the package using :  !python3 -m pip -q install git+https://github.com/alok-ai-lab/pyDeepInsight.git#egg=pyDeepInsight there was no issue in this. But when I try to do something like : from pyDeepInsight import ImageTransformer I'm getting an import error like : cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.8/dist-packages/PIL/_util.py) . Does anyone know what im doing wrong or does someone have a solution to this.

**Comment by kaboroevich** [comment]
Based on [this similar error](https://github.com/obss/sahi/discussions/781), could you try restarting the runtime after installing pyDeepInsight and see if that resolves the issue.

If that doesn't work, can you post the full exception traceback?
