### ISSUE TITLE
running bug

### ISSUE THREAD

**Issue by engsarah2050** [alok-ai-lab/pyDeepInsight#33]
the code produces the following messege :
[/usr/local/lib/python3.10/dist-packages/pyDeepInsight/image_transformer.py](https://localhost:8080/#) in <module>
     14 import inspect
     15 
---> 16 from .utils import asymmetric_greedy_search
     17 
     18 class ManifoldLearner(Protocol):

ModuleNotFoundError: No module named 'pyDeepInsight.utils'

when running the offical examples ,when i folked the repo and used the absolute path the  
problem stil exists.
ps
this happed after the last updated

**Comment by kaboroevich** [comment]
Thank you for the notification. The setup.py was not correctly modified to deal with subpackages. I believe the commit 06375bf should solve this issue.
