### ISSUE TITLE
feat_idx  and genes

### ISSUE THREAD

**Issue by LorenzoBioinfo** [alok-ai-lab/pyDeepInsight#35]
Hi,
I'm using trying to use your script "Feature Selection Example".
I got this error : 
 for cat, idx in feat_idx.items():
        print(idx)
----> 4     feature_names = genes[idx]
         print(f"{idx.shape[0]:5} features selected for {np.unique(y_train)[cat]:4}: {', '.join(feature_names[1:10])}...")
IndexError: index 1298 is out of bounds for axis 0 with size 43

If I understand well, genes should be  input feature names and feat_idx their indexes. I don't understand why feat_idx gives me such high indices if I only have 43 features.

**Comment by kaboroevich** [comment]
I think I will need to see the rest of the modified code sections to fully understand what the issue may be.

**Comment by LorenzoBioinfo** [comment]
Thank you! Sure.
Basically, I've used the first tutorial [Classification of TCGA data using SqueezeNet](https://github.com/alok-ai-lab/pyDeepInsight/blob/master/examples/pytorch_squeezenet.ipynb) to create and train the model. Then, I tried to follow the second part to extract the features.

Here my code 

```
y = merged['Target'].values
X = merged.iloc[:, :-1].values
genes = merged.iloc[:, :-1].columns.to_numpy()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y)

le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)
num_classes = np.unique(y_train_enc).size

distance_metric = 'cosine'
reducer = TSNE(
    n_components=2,
    metric=distance_metric,
    init='random',
    learning_rate='auto',
    n_jobs=-1
)

pixel_size = (227,227)
it = ImageTransformer(
    feature_extractor=reducer, 
    pixels=pixel_size)

it.fit(X_train, y=y_train, plot=True)
X_train_img = it.transform(X_train)
X_test_img = it.transform(X_test)


model = torchvision.models.squeezenet1_1(weights='DEFAULT')
model.classifier.append(nn.Flatten())
_ = model.classifier.append(nn.Linear(1000, num_classes))

preprocess = transforms.Compose([
    transforms.ToTensor()
])

X_train_tensor = torch.stack([preprocess(img) for img in X_train_img]).float()
y_train_tensor = torch.from_numpy(le.fit_transform(y_train))

X_test_tensor = torch.stack([preprocess(img) for img in X_test_img]).float()
y_test_tensor = torch.from_numpy(le.transform(y_test))

batch_size = 32

trainset = TensorDataset(X_train_tensor, y_train_tensor)
trainloader = DataLoader(trainset, batch_size=batch_size, shuffle=True)

testset = TensorDataset(X_test_tensor, y_test_tensor)
testloader = DataLoader(testset, batch_size=batch_size, shuffle=False)


criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(
    model.parameters(),
    lr=1e-04,
    #momentum=0.8,
    weight_decay=1e-05
)

model.train()
model.to(device)
for epoch in range(120):

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    # print epoch statistics
    if not (epoch % 20):
        print(f'[{epoch}] loss: {running_loss / len(X_train_tensor) * batch_size:.3f}')
print(f'[{epoch}] loss: {running_loss / len(X_train_tensor) * batch_size:.3f}')




###### Feature extraction

cm_method='GradCAM'
camfs = CAMFeatureSelector(
    model=model,
    it=it,
    cam_method=cm_method
)

fl_method = "mean"
class_cam = camfs.calculate_class_activations(X_train_tensor, y_train_tensor, batch_size=100, flatten_method=fl_method)

fs_threshold = 0.4
feat_idx = camfs.select_class_features(cams=class_cam, threshold=fs_threshold)

for cat, idx in feat_idx.items():
    print(idx)
    feature_names = genes[idx]
   print(feature_names)


```

**Comment by kaboroevich** [comment]
Thank you for the code. I ran it with a test set of similar feature size and also received an error. I will look into this and try to get back to you soon.

**Comment by kaboroevich** [comment]
I believe the updated code should fix your issue. Please reinstall pyDeepInsight from GitHub and try your code again.

Thank you for finding this.

**Comment by LorenzoBioinfo** [comment]
Thank you! It works now!

**Comment by LorenzoBioinfo** [comment]
In the tutorial, I think there's another error when you print feature name.

```
for cat, idx in feat_idx.items():
    print(idx)
    feature_names = genes[idx]
    print(f"{idx.shape[0]:5} features selected for {np.unique(y_train)[cat]:4}: {', '.join(feature_names[1:10])}")

```
Should be  '...'.join(feature_names[0:10]. 

Thank you again! Your model is fantastic!

**Comment by kaboroevich** [comment]
>     print(f"{idx.shape[0]:5} features selected for {np.unique(y_train)[cat]:4}: {', '.join(feature_names[1:10])}")

I don't see this line in either example page. 

It should be noted that `np.unique(y_train)` is not guaranteed to give the same order as the label encoder used to generate the category labels. In the example, a `le_mapping` variable is created using the label encoder object to ensure the `cat` value corresponds to the correct original category.
