### ISSUE TITLE
Getting Started with DeepInsight Implementation

### ISSUE THREAD

**Issue by abbasnafiu** [alok-ai-lab/pyDeepInsight#37]
Good day Sirs,

I am a research student, currently working on Image-Based Android Malware Detection.
I found DeepInsight Methodology useful for my work. I need it for transforming android app extracted features to images for CNN architecture.
Whenever I try to install DeepInsight on my PC, I encounter this error.
Find the attached

![Screenshot (88)](https://github.com/alok-ai-lab/pyDeepInsight/assets/22841447/d1a69a35-9d48-47ef-a19a-75ed67c032e3)

**Comment by kaboroevich** [comment]
It looks to be an issue with `git clone` rather than pyDeepInsight; Possibly Windows specific. Rather than installing directly from GitHub, try downloading the repository and installing it from that.

1. Click on '<> Code>' then 'Download ZIP'
2. Save pyDeepInsight-master.zip to a local folder
3. Run `python3 -m pip install /path/to/pyDeepInsight-master.zip`

**Comment by abbasnafiu** [comment]
OK. I am very grateful for this beneficial response

**Comment by abbasnafiu** [comment]
> It looks to be an issue with `git clone` rather than pyDeepInsight; Possibly Windows specific. Rather than installing directly from GitHub, try downloading the repository and installing it from that.
> 
> 1. Click on '<> Code>' then 'Download ZIP'
> 2. Save pyDeepInsight-master.zip to a local folder
> 3. Run `python3 -m pip install /path/to/pyDeepInsight-master.zip`

Thanks for your responses.
I was able to install the package. 
1. How can I run the package to convert my extracted features to Images. 
2. Inside which directory path will I insert my dataset

Thanks as you reply

**Comment by kaboroevich** [comment]
Please see the [pyTorch SqueezeNet example](https://github.com/alok-ai-lab/pyDeepInsight/blob/master/examples/pytorch_squeezenet.ipynb) for example code on how initialize the ImageTransformer class and use it to generate images.

**Comment by abbasnafiu** [comment]
Okay. thanks
