### ISSUE TITLE
Fail to import ImageTransformer

### ISSUE THREAD

**Issue by shibataryohei** [alok-ai-lab/pyDeepInsight#39]
Hi,

Recently I've got an error when I import ImageTransformer from pyDeepInsight as below. Do you have any solution? I ran this code in Google Colab.

```python
!python3 -m pip -q install git+https://github.com/alok-ai-lab/pyDeepInsight.git#egg=pyDeepInsight
from pyDeepInsight import ImageTransformer

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-12-a2722f987c84>"](https://localhost:8080/#), line 3, in <cell line: 3>
    from pyDeepInsight import ImageTransformer

  File "/content/pyDeepInsight/pyDeepInsight/__init__.py", line 1, in <module>
    from .image_transformer import ImageTransformer

  File "/content/pyDeepInsight/pyDeepInsight/image_transformer.py", line 350
    img_matrix[:, *c] = X[:, np.where(idx == i)[0]].mean(axis=1)
                  ^
SyntaxError: invalid syntax
```

Thank you,
Ryohei

**Comment by faberrocalv** [comment]
Hi!
I hace the same issue both in colab or after installing it in my pc with the installation command.

**Comment by shibataryohei** [comment]
> Hi! I have the same issue both in colab or after installing it in my pc with the installation command.

Hi faberrocalv,

Delete `*` in line 350 of `image_transformer.py` then that worked for me. Hope this works for you!

**Comment by kaboroevich** [comment]
Thanks for the report. This appears to be a syntax only valid in python 3.11. A fix is in progress.
