### ISSUE TITLE
How to plot the figure in the README.md

### ISSUE THREAD

**Issue by ljw-struggle** [alok-ai-lab/pyDeepInsight#45]
![image](https://github.com/alok-ai-lab/pyDeepInsight/assets/24591769/e30bace2-5885-48ff-a8a2-c938c238fbab)

I'm very interested in plotting this figure. Can you give a demo script to plot this figure?

Sincerely,
Jiawei

**Comment by kaboroevich** [comment]
I've created [a Google collab linked gist](https://gist.github.com/kaboroevich/397b9430716a03e20fff04b02487e66a) that generates a similar image with generated data. I am not sure it is the optimal way to generate subplots/subfigures. Also, to ensure the manifold mapping is preserved between the two discretization methods, private internal attributes and methods need to be accessed.

**Comment by ljw-struggle** [comment]
> I've created [a Google collab linked gist](https://gist.github.com/kaboroevich/397b9430716a03e20fff04b02487e66a) that generates a similar image with generated data. I am not sure it is the optimal way to generate subplots/subfigures. Also, to ensure the manifold mapping is preserved between the two discretization methods, private internal attributes and methods need to be accessed.

Thank you for your answer, it helps me a lot!
