### ISSUE TITLE
MRep seems to increase the number of input samples

### ISSUE THREAD

**Issue by abelavit** [alok-ai-lab/pyDeepInsight#49]
Hi, I am trying out MRep tool and have a question on the number of images after transformation. The tool seems to increase the number of samples fed into it. For instance, if I have a training sample size of 10, the train_input size becomes [60, 3, 224, 224]. Is this a normal behavior of the algorithm?

Thanks.

**Comment by kaboroevich** [comment]
Yes, this is expected. MRep stands for multiple representations. In your case it appears you created 6 representations (images) per sample.

**Comment by kaboroevich** [comment]
We will close this issue as completed. If you have any additional questions about this topic or have a suggestion to make this clearer in the README or example, feel free to reply to this thread.
